name: My first workflow

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
            - name: Welcome message
              run: echo "Welcome to my first Git Action Job"
            
            - name: List Files
              run: ls
            
            - name: Read Files
              run: cat README.md